export const NOTE_TAGS = [
  {
    label: "Getting Started",
    value: "getting-started",
  },
  {
    label: "Onboarding",
    value: "onboarding",
  },
  {
    label: "User Flow",
    value: "user-flow",
  },
  {
    label: "UX",
    value: "ux",
  },
  {
    label: "Bugs",
    value: "bugs",
  },
  {
    label: "V2",
    value: "v2",
  },
];

export const DUMMY_CONTACTS = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    role: "Developer",
    createdAt: 1632728400,
  },
  {
    id: 2,
    firstName: "Alice",
    lastName: "Smith",
    email: "alice.smith@example.com",
    role: "Designer",
    createdAt: 1632642000,
  },
  {
    id: 3,
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob.johnson@example.com",
    role: "Manager",
    createdAt: 1632555600,
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@example.com",
    role: "Analyst",
    createdAt: 1632469200,
  },
  {
    id: 5,
    firstName: "Michael",
    lastName: "Clark",
    email: "michael.clark@example.com",
    role: "Developer",
    createdAt: 1632382800,
  },
  {
    id: 6,
    firstName: "Sara",
    lastName: "Williams",
    email: "sara.williams@example.com",
    role: "Product Manager",
    createdAt: 1632296400,
  },
  {
    id: 7,
    firstName: "Daniel",
    lastName: "Taylor",
    email: "daniel.taylor@example.com",
    role: "QA Tester",
    createdAt: 1632210000,
  },
  {
    id: 8,
    firstName: "Olivia",
    lastName: "Brown",
    email: "olivia.brown@example.com",
    role: "Manager",
    createdAt: 1632123600,
  },
  {
    id: 9,
    firstName: "Henry",
    lastName: "Anderson",
    email: "henry.anderson@example.com",
    role: "Designer",
    createdAt: 1632037200,
  },
  {
    id: 10,
    firstName: "Sophia",
    lastName: "Miller",
    email: "sophia.miller@example.com",
    role: "Developer",
    createdAt: 1631950800,
  },
  {
    id: 11,
    firstName: "David",
    lastName: "Roberts",
    email: "david.roberts@example.com",
    role: "Product Manager",
    createdAt: 1631864400,
  },
  {
    id: 12,
    firstName: "Emma",
    lastName: "Turner",
    email: "emma.turner@example.com",
    role: "Analyst",
    createdAt: 1631778000,
  },
  {
    id: 13,
    firstName: "Liam",
    lastName: "Baker",
    email: "liam.baker@example.com",
    role: "QA Tester",
    createdAt: 1631691600,
  },
  {
    id: 14,
    firstName: "Ava",
    lastName: "Carter",
    email: "ava.carter@example.com",
    role: "Designer",
    createdAt: 1631605200,
  },
  {
    id: 15,
    firstName: "Logan",
    lastName: "Evans",
    email: "logan.evans@example.com",
    role: "Developer",
    createdAt: 1631518800,
  },
  {
    id: 16,
    firstName: "Grace",
    lastName: "Fisher",
    email: "grace.fisher@example.com",
    role: "Manager",
    createdAt: 1631432400,
  },
  {
    id: 17,
    firstName: "Jack",
    lastName: "Gibson",
    email: "jack.gibson@example.com",
    role: "Designer",
    createdAt: 1631346000,
  },
  {
    id: 18,
    firstName: "Ella",
    lastName: "Hayes",
    email: "ella.hayes@example.com",
    role: "Developer",
    createdAt: 1631259600,
  },
  {
    id: 19,
    firstName: "Caleb",
    lastName: "Iverson",
    email: "caleb.iverson@example.com",
    role: "Product Manager",
    createdAt: 1631173200,
  },
  {
    id: 20,
    firstName: "Mia",
    lastName: "Jackson",
    email: "mia.jackson@example.com",
    role: "QA Tester",
    createdAt: 1631086800,
  },
];

export const DUMMY_NOTES = [
  {
    id: 1,
    title: "Website Redesign",
    description: `Redesign the company website to improve user experience and incorporate the latest design trends.`,
    tags: [NOTE_TAGS[3], NOTE_TAGS[5]],
    createdAt: "1696213778",
    status: "Created",
    assignedContact: DUMMY_CONTACTS[0],
  },
  {
    id: 2,
    title: "New Employee Onboarding",
    description: `Create an onboarding checklist and training materials for new employees joining the company.`,
    tags: [NOTE_TAGS[0], NOTE_TAGS[1]],
    createdAt: "1696192178",
    status: "Drafted",
    assignedContact: DUMMY_CONTACTS[1],
  },
  {
    id: 3,
    title: "App Navigation Review",
    description: `Evaluate and propose improvements to the app navigation to enhance user flow and accessibility.`,
    tags: [NOTE_TAGS[2], NOTE_TAGS[3]],
    createdAt: "1696127378",
    status: "Drafted",
    assignedContact: DUMMY_CONTACTS[2],
  },
];
